name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo check
  docs:
    name: cargo docs
    needs: check
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo doc --no-deps
      - run: rm -f target/doc/.lock target/doc/settings.html target/doc/help.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc/
  deploy:
    name: deploy pages
    needs: docs
    runs-on: ubuntu-latest
   
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
