name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo check
  docs:
    name: cargo check
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo doc --no-deps
      - run: tar -czf target/doc.tar.gz target/doc/*
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: target/doc.tar.gz
